// Code generated by cmd/reset - DO NOT EDIT.

package handler

func (r *RequestContext) Reset() {
	if r == nil {
		return
	}
	r.userID = ""
	r.timestamp = 0
	if r.headers != nil {
		clear(r.headers)
	}
	r.params = r.params[:0]
}
