package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

type structInfo struct {
	name   string
	fields []*ast.Field
}

type packageInfo struct {
	path    string
	name    string
	structs []*structInfo
}

func main() {
	packages := make(map[string]*packageInfo)

	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			if strings.HasPrefix(info.Name(), ".") ||
				strings.HasPrefix(info.Name(), "_") ||
				info.Name() == "vendor" ||
				info.Name() == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		parseGoFile(path, root, packages)
		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range packages {
		if len(pkg.structs) > 0 {
			generateResetFile(pkg)
		}
	}
}

func parseGoFile(filePath string, root string, packages map[string]*packageInfo) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		log.Printf("skip file %s: %v\n", filePath, err)
		return
	}

	pkgName := file.Name.Name
	pkgDir := filepath.Dir(filePath)

	if _, exists := packages[pkgDir]; !exists {
		packages[pkgDir] = &packageInfo{
			path:    pkgDir,
			name:    pkgName,
			structs: []*structInfo{},
		}
	}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		hasGenerateReset := false
		if genDecl.Doc != nil {
			for _, comment := range genDecl.Doc.List {
				if strings.TrimSpace(comment.Text) == "// generate:reset" {
					hasGenerateReset = true
					break
				}
			}
		}

		if !hasGenerateReset {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			packages[pkgDir].structs = append(packages[pkgDir].structs, &structInfo{
				name:   typeSpec.Name.Name,
				fields: structType.Fields.List,
			})
		}
	}
}

func generateResetFile(pkg *packageInfo) {
	filePath := filepath.Join(pkg.path, "reset.gen.go")

	f, err := os.Create(filePath)
	if err != nil {
		log.Printf("cannot create %s: %v\n", filePath, err)
		return
	}
	defer func() {
		if err := f.Close(); err != nil {
			log.Printf("failed to close file %s: %v", filePath, err)
		}
	}()

	if _, err := fmt.Fprintf(f, "// Code generated by cmd/reset - DO NOT EDIT.\n\n"); err != nil {
		log.Printf("failed to write to file %s: %v", filePath, err)
	}

	if _, err := fmt.Fprintf(f, "package %s\n\n", pkg.name); err != nil {
		log.Printf("failed to write to file %s: %v", filePath, err)
	}

	for _, si := range pkg.structs {
		if err := generateResetMethod(f, si); err != nil {
			log.Printf("failed to generate reset for %s: %v", si.name, err)
			return
		}
	}
}

func generateResetMethod(f *os.File, si *structInfo) error {
	if _, err := fmt.Fprintf(f, "func (r *%s) Reset() {\n", si.name); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "\tif r == nil {\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "\t\treturn\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "\t}\n\n"); err != nil {
		return err
	}

	for _, field := range si.fields {
		if len(field.Names) == 0 {
			continue
		}

		for _, name := range field.Names {
			fieldName := name.Name
			resetCode := generateResetCode(fieldName, field.Type)
			if resetCode != "" {
				if _, err := fmt.Fprintf(f, "%s\n", resetCode); err != nil {
					return err
				}
			}
		}
	}

	if _, err := fmt.Fprintf(f, "}\n\n"); err != nil {
		return err
	}

	return nil
}

func generateResetCode(fieldName string, fieldType ast.Expr) string {
	fieldRef := "r." + fieldName

	switch t := fieldType.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"uintptr", "float32", "float64":
			return fmt.Sprintf("\t%s = 0", fieldRef)
		case "string":
			return fmt.Sprintf("\t%s = \"\"", fieldRef)
		case "bool":
			return fmt.Sprintf("\t%s = false", fieldRef)
		default:
			return fmt.Sprintf("\tif resetter, ok := %s.(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}", fieldRef)
		}

	case *ast.StarExpr:
		innerType := t.X
		zeroValue := getZeroValueForType(innerType)

		if _, isPtr := innerType.(*ast.StarExpr); isPtr || isPrimitive(innerType) {
			return fmt.Sprintf("\tif %s != nil {\n\t\t*%s = %s\n\t}", fieldRef, fieldRef, zeroValue)
		}

		return fmt.Sprintf("\tif %s != nil {\n\t\tif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n\t\t\tresetter.Reset()\n\t\t}\n\t}", fieldRef, fieldRef)

	case *ast.ArrayType:
		return fmt.Sprintf("\t%s = %s[:0]", fieldRef, fieldRef)

	case *ast.MapType:
		return fmt.Sprintf("\tif %s != nil {\n\t\tclear(%s)\n\t}", fieldRef, fieldRef)

	default:
		return ""
	}
}

func isPrimitive(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return false
	}

	switch ident.Name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "float32", "float64", "string", "bool", "byte", "rune":
		return true
	default:
		return false
	}
}

func getZeroValueForType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"uintptr", "float32", "float64":
			return "0"
		case "string":
			return "\"\""
		case "bool":
			return "false"
		default:
			return "nil"
		}
	case *ast.StarExpr:
		return "nil"
	default:
		return "nil"
	}
}
