package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type structInfo struct {
	name   string
	fields []*ast.Field
}

type packageInfo struct {
	path    string
	name    string
	structs []*structInfo
}

const resetFileTemplate = `// Code generated by cmd/reset - DO NOT EDIT.

package {{ .PackageName }}

{{- range .Structs }}

func (r *{{ .Name }}) Reset() {
	if r == nil {
		return
	}
{{- range .Fields }}
{{ . }}
{{- end }}
}
{{- end }}
`

type resetFileModel struct {
	PackageName string
	Structs     []resetStructModel
}

type resetStructModel struct {
	Name   string
	Fields []string
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	packages, err := collectPackages(root)
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range packages {
		if len(pkg.structs) == 0 {
			continue
		}

		if err := generateResetFile(pkg); err != nil {
			log.Fatalf("failed generating reset for package %s: %v", pkg.name, err)
		}
	}
}

func collectPackages(root string) (map[string]*packageInfo, error) {
	packages := make(map[string]*packageInfo)

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			if strings.HasPrefix(info.Name(), ".") ||
				strings.HasPrefix(info.Name(), "_") ||
				info.Name() == "vendor" ||
				info.Name() == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}

		if !isGoSourceFile(path) {
			return nil
		}

		return parseGoFile(path, packages)
	})

	return packages, err
}

func isGoSourceFile(path string) bool {
	if !strings.HasSuffix(path, ".go") {
		return false
	}
	if strings.HasSuffix(path, "_test.go") {
		return false
	}
	if strings.HasSuffix(path, ".gen.go") {
		return false
	}
	return true
}

func parseGoFile(filePath string, packages map[string]*packageInfo) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil // skip broken files
	}

	pkgDir := filepath.Dir(filePath)
	pkgName := file.Name.Name

	pkg := packages[pkgDir]
	if pkg == nil {
		pkg = &packageInfo{
			path: pkgDir,
			name: pkgName,
		}
		packages[pkgDir] = pkg
	}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		if !hasResetDirective(genDecl) {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			pkg.structs = append(pkg.structs, &structInfo{
				name:   typeSpec.Name.Name,
				fields: structType.Fields.List,
			})
		}
	}

	return nil
}

func hasResetDirective(genDecl *ast.GenDecl) bool {
	if genDecl.Doc == nil {
		return false
	}

	for _, comment := range genDecl.Doc.List {
		if strings.TrimSpace(comment.Text) == "// generate:reset" {
			return true
		}
	}

	return false
}

func generateResetFile(pkg *packageInfo) error {
	model := buildModel(pkg)

	tmpl, err := template.New("reset").Parse(resetFileTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer

	if err := tmpl.Execute(&buf, model); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	outputPath := filepath.Join(pkg.path, "reset.gen.go")
	return os.WriteFile(outputPath, formatted, 0644)
}

func buildModel(pkg *packageInfo) resetFileModel {
	model := resetFileModel{
		PackageName: pkg.name,
	}

	for _, si := range pkg.structs {
		sm := resetStructModel{
			Name: si.name,
		}

		for _, field := range si.fields {
			if len(field.Names) == 0 {
				continue
			}

			for _, name := range field.Names {
				code := generateResetCode(name.Name, field.Type)
				if code != "" {
					sm.Fields = append(sm.Fields, code)
				}
			}
		}

		model.Structs = append(model.Structs, sm)
	}

	return model
}

func generateResetCode(fieldName string, fieldType ast.Expr) string {
	fieldRef := "r." + fieldName

	switch t := fieldType.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"uintptr", "float32", "float64":
			return "\t" + fieldRef + " = 0"
		case "string":
			return "\t" + fieldRef + ` = ""`
		case "bool":
			return "\t" + fieldRef + " = false"
		default:
			return "\tif resetter, ok := " + fieldRef + ".(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}"
		}

	case *ast.StarExpr:
		return "\tif " + fieldRef + " != nil {\n\t\t*" + fieldRef + " = " + getZeroValueForType(t.X) + "\n\t}"

	case *ast.ArrayType:
		return "\t" + fieldRef + " = " + fieldRef + "[:0]"

	case *ast.MapType:
		return "\tif " + fieldRef + " != nil {\n\t\tclear(" + fieldRef + ")\n\t}"

	default:
		return ""
	}
}

func getZeroValueForType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return `""`
		case "bool":
			return "false"
		default:
			return "0"
		}
	default:
		return "nil"
	}
}
